apiVersion: v1
kind: Pod
metadata:
      name: nginx-custom-pod
      labels:
        env: development
        launchedby: kamal-sharma
spec:
   containers:
   - name: my-nginx
     image: nginx:alpine
     ports:
     - containerPort: 80
     livenessProbe:
          httpGet:
              path: /index.html
              port: 80
          initialDelaySeconds: 15
          periodSeconds: 2
          failureThreshold: 1